bootstrap.sh failed detect PYTHON_ROOT with Python3
Bootstrap failed on the print statement with Python 3.x, because the print statement is converted to a function in Python3
Adding parentheses fixes the problem and is backwards compatible with Python 2.x

===
Detecting Python version... 3.4
Detecting Python root...   File "<string>", line 1
    import sys; print sys.prefix
                        ^
SyntaxError: invalid syntax
===

Fixes:
Ticket #6946 https://svn.boost.org/trac/boost/ticket/6946
Ticket #5677 https://svn.boost.org/trac/boost/ticket/5677